[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "open_project"
authors = [{name = "SabNK", email = "sabnk@mail.ru"}]
dynamic = ["version", "description"]
